language: node_js 
node_js: stable # 要安装的node版本为当前的稳定版 
cache: 
  directories: 
  - node_modules # 要缓存的文件夹 
install: 
  - npm install
script: 
  - hexo clean 
  - hexo g 

after_script: # 最后执行的命令   
  - cd ./public 
  - git init 
  - git config user.name "pinfanyang" 
  - git config user.email "pinfanyang@ahut.edu.cm" 
  - git add . - git commit -m "代码自动部署完成!" 
  - git push --force --quiet "https://${Personal_Blog_Token}@${GH_REF}" master:gh-pages 

branches: 
  only: 
    - main # 触发持续集成的分支
    
env: 
  global: 
    - GH_REF: github.com/pinfanyang/Personal_Blog.git # 就是你github上存放静态博客最终文件的仓库地址末尾加上.git


